name: Build Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref (branch / tag or hash) to build'
        required: true 
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:

    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}

    - name: Build APK
      run: make tailscale-debug.apk

    - name: Archive Debug Build
      uses: actions/upload-artifact@v3
      with:
        path: ./**/*.apk